project_name: backup-github

version: 2

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: macos
    goos:
      - darwin
    main: ./cmd/backup-github/main.go
    binary: backup-github
    ldflags:
      - -s -w -X github.com/ChrisWiegman/backup-github/internal/backup.Version={{.Version}} -X github.com/ChrisWiegman/backup-github/internal/backup.Timestamp={{.Date}}

archives:
  - id: macos
    ids:
      - macos
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE.txt
      - CHANGELOG.md

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

changelog:
  disable: false

homebrew_casks:
  - repository:
      owner: ChrisWiegman
      name: homebrew-backup-github
      branch: main
    name: backup-github
    license: MIT
    homepage: https://github.com/ChrisWiegman/backup-github
    description: A simple CLI utility, written in GoLang, to backup all of your GitHub repos.
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/backup-github"]
          end
